#!/bin/sh -ex

if [ "${PLUGIN_DEPLOYMENT_POSTFIX}" != "" ]; then
    export PLUGIN_CONTAINER=${CIRCLE_PROJECT_REPONAME}-${PLUGIN_DEPLOYMENT_POSTFIX}
    export PLUGIN_DEPLOYMENT=${CIRCLE_PROJECT_REPONAME}-${PLUGIN_DEPLOYMENT_POSTFIX}
fi

export CIRCLE_PROJECT_REPONAME=worker-optimizer-v2
export BUILD_REF=$(if [ -z "$CIRCLE_TAG" ]; then echo ${CIRCLE_BRANCH/\//-}-${CIRCLE_SHA1:0:7}; else echo $CIRCLE_TAG; fi)
export DST_NAMESPACE=$(if [ -z "$CIRCLE_TAG" ]; then echo dev; else echo staging; fi)
export PLUGIN_TAG=${BUILD_REF}
export PLUGIN_REPO=724009402066.dkr.ecr.eu-west-1.amazonaws.com/${CIRCLE_PROJECT_REPONAME}
export PLUGIN_CONTAINER=${CIRCLE_PROJECT_REPONAME}
export PLUGIN_DEPLOYMENT=${CIRCLE_PROJECT_REPONAME}
export PLUGIN_NAMESPACE=${DST_NAMESPACE}
export PLUGIN_KUBERNETES_SERVER=${KUBERNETES_SERVER_DEV}
export PLUGIN_KUBERNETES_TOKEN=${KUBERNETES_TOKEN_DEV}
/bin/update.sh